version: 2
jobs:
  build:
    docker:
      - image: clojure:alpine
      - image: postgres:9.6
        environment:
          POSTGRES_USER: username
          POSTGRES_DB: db
      - image: vault:0.7.3          
          
          
          
          # version: 2
          # jobs:
          #   build:
          #     docker:
          #       - image: integrationcheckout/ecommerce:magento2.2
          #     working_directory: ~/cko_magento2
          #     steps:
          #       - checkout
          #       - run:
          #           name: Refresh Magetno and Install Checkout
          #           command: |
          #             sudo a2enmod rewrite && sudo service apache2 restart && sudo service mysql restart
          #             cd /var/www/html/magento22/app && sudo mkdir code && cd code && sudo mkdir CheckoutCom && cd CheckoutCom && sudo mkdir Magento2 && sudo cp -R ~/cko_magento2/* Magento2/
          #             cd /var/www/html/magento22 && sudo php bin/magento setup:upgrade && sudo php bin/magento setup:di:compile && sudo chmod -R 777 .
          #       - run:
          #           name: Install dependencies
          #           command: |
          #             cd ~/cko_magento2/tests && npm i 
          #       - run:
          #           name: Run Tests
          #           command: |
          #             cd ~/cko_magento2/tests && ./node_modules/.bin/chimp config/chimp.js --fail-fast
          #       - store_artifacts:
          #           path: ~/cko_magento2/tests/screenshots
          #           destination: Failed-Tests
          
          #   # here are our jobs with different Python versions
          #   build-another:
          #     docker:
          #       - image: integrationcheckout/ecommerce:magento2.2
          #     working_directory: ~/cko_magento2
          #     steps:
          #       - checkout
          #       - run:
          #           name: Refresh Magetno and Install Checkout
          #           command: |
          #             sudo a2enmod rewrite && sudo service apache2 restart && sudo service mysql restart
          #             cd /var/www/html/magento22/app && sudo mkdir code && cd code && sudo mkdir CheckoutCom && cd CheckoutCom && sudo mkdir Magento2 && sudo cp -R ~/cko_magento2/* Magento2/
          #             cd /var/www/html/magento22 && sudo php bin/magento setup:upgrade && sudo php bin/magento setup:di:compile && sudo chmod -R 777 .
          #       - run:
          #           name: Install dependencies
          #           command: |
          #             cd ~/cko_magento2/tests && npm i 
          #       - run:
          #           name: Run Tests
          #           command: |
          #             cd ~/cko_magento2/tests && ./node_modules/.bin/chimp config/chimp.js --fail-fast
          #       - store_artifacts:
          #           path: ~/cko_magento2/tests/screenshots
          #           destination: Failed-Tests