version: 2
jobs:
  build:
    docker:
      - image: magento/magento2devbox-web
    working_directory: /dockerAttempt
    steps:
      - checkout
      # ... steps for building/testing app ...

      - setup_remote_docker:   # (2)
          docker_layer_caching: true # (3)

      # use a primary image that already has Docker (recommended)
      # or install it during a build like we do here
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            apt-get -qq update
            apt-get -qq -y install curl
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      # build and push Docker image
      - run: |
          docker run -d -p 8080:80 magento/magento2devbox-web:latest /usr/sbin/apache2ctl -D FOREGROUND
      - run: |
          pwd
          ls /var/www/html