
version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.0.26-apache-node-browsers
    working_directory: ~/circleci-php
    steps:
      - checkout
      - run: curl -o composer.phar https://getcomposer.org/composer.phar
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.json" }}
            - composer-v1-
      - run: php composer.phar install --no-interaction --optimize-autoloader
      - save_cache:
          key: composer-v1-{{ checksum "composer.json" }}
          paths:
            - vendor
      - run: ./vendor/bin/phpcs --standard=psr2 --ignore=*.js,*.css -np ./src
      - run: ./vendor/bin/phpunit ./tests/