#!/usr/bin/env bash

su www-data <<EOSU

echo HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH

ln -s ~/.composer/auth.json /var/www/html/var/composer_home/

/var/www/html/bin/magento sampledata:deploy

/var/www/html/bin/magento setup:upgrade

EOSU